server:
  port: 8080
  contextPath: /rs
  compression:
    enabled: false
    mime-types: text/html,text/css,application/javascript,application/json
spring:  
  datasource:
      url: jdbc:postgresql://localhost:5432/test
      username: postgres
      password: root
      driverClassName: org.postgresql.Driver
      testOnBorrow: true
      testWhileIdle: true
      validationQuery: select 1;
      maxActive: 100  
#security:
  #oauth2:
   # client:
    #  client-id: acme
     # client-secret: acmesecret
      #access-token-uri: http://localhost:8080/oauth/token
      #user-authorization-uri: http://localhost:8080/oauth/authorize
    #resource:
      #user-info-uri: http://localhost:8080/me